### ISSUE TITLE
Current issues that need to be addressed

### ISSUE THREAD

**Issue by Merculous** [32Bites/PyKeys#1]
So far, I've found that some versions of iOS give out an error of printing a version's rootfs key, and some versions also just don't give out any keys as the buildid gets parsed as "\n". Also, there's an oof at the bottom of PyKeys the input() before mainmenu() needs to be removed because it hangs where it shouldn't be receiving any more user input.

**Comment by 32Bites** [comment]
I will look into the issues you have stated above. May I ask what firmware versions and identifier? Now on the extra input(), I had that for debugging, and I forgot to remove it. Thank you though.
